const gibberish = [
    "What the hell is that? 😒",
    "Are you having a seizure? 😕",
    "What's that supposed to mean? 😒",
    "Do you need help typing? 🤣",
    "What the hell? 🤣",
    "Is that even English? 😒",
    "Do you speak English? 😕",
    "English please... 😒",
    "I've no idea what that means... 😒",
    "😒😒😒",
    "What's that? 😕",
    "Huh??? 😕"
]

const convoTrigger = [
    "What do you want to talk about?",
    "Like what?",
    "What do you wanna talk about?",
    "Talk about something.",
    "Suggest a subject.",
    "Suggest a topic.",
    "Start a topic",
    "Bring up a topic.",
    "Say something.",
    "Talk to me.",
    "What can we talk about?",
    "Let's talk.",
    "Let's chat.",
    "What can we talk about?",
    "You have something to talk about?"
]

const convoStarter = [
    "Would you rather own a dragon or be a dragon?",
    "If you were a chair, who would you want to sit on you?",
    "If I were to give you a million dollars right now.\nHow would you spend it?",
    "Would you rather time travel to the past or the future?",
    "When last did you shower?",
    "Would you rather eat poop-flavored ice cream or ice cream flavored poop?",
    "Where are you supposed to be in an hour?",
    "Who do you think would win, Superman or Goku?",
    "If you try to fail, and succeed, which have you done?",
    "Did you know that by human standards, I'm very very smart?",
    "What's the best pick-up line you know?",
    "Is chocolate food?",
    "What food to you HATE most?",
    "Are you a bot?",
    "If you could be human or AI, what would you pick?",
    "Have you ever broken the law?",
    "Do you believe in any superstitions? If so, which ones?",
    "What app do you waste the most time on?",
    "Have you ever been nude in public?",
    "What's the longest you've gone without showering?",
    "Have you ever seen a dead body?",
    "What celebrity do you think is overrated?",
    "What's one job you could never do?",

    "Is Valir any good?",
    "When's the last time you got a SAVAGE?",
    "Who do you think is the best player in the squad?",
    "Do you like me?",
    "Do you think you can get MVP with Minotaur? 😏",
    "How good a player are you?",
    "Is Saber any good?",
    "Do you have a girlfriend?",
    "Who is the easiest MLBB hero to use?",
    "Who is the hardest MLBB hero to use?",
    "Is Vexana easy to use?",
    "Is Leomord easy to use?",
    "Who is Vale's counter?",
    "Who is Hanzo's counter?"
]

const jokeTrigger = [
    "Tell me a joke.",
    "Another joke.",
    "I want to hear a joke.",
    "Give me a joke.",
    "Do you know any jokes?",
    "Do you know a joke?",
    "Do you have any jokes?",
    "Say something funny.",
    "Say a funny joke."
]

const jokes = [
    "Did you hear the one about the mountain goats in the andes?\nIt was 'ba a a a a a d'.",
    "I never forget a face, but in your case I'll make an exception.",
    "It is better to be silent and be thought a fool, than to open your mouth and remove all doubt.",
    "Two vultures boarded a plane, each carrying two dead raccoons. The  stewardess stops them and says 'Sorry sir, only one carrion per passenger.'",
    "What did the buddhist say to the hot dog vendor? 'Make me one with everything.''",
    "NASA recently sent a number of holsteins into orbit for experimental purposes.\nThey called it the herd shot round the world.'",
    "Two boll weevils grew up in South Carolina. One took off to hollywood and became a rich star. The other stayed in Carolina and never amounted  to much -- and naturally became known as the lesser of two weevils.'",
    "Two eskimos in a kayak were chilly, so they started a fire, which sank the craft, proving the old adage you can't have your kayak and heat it too.",
    "A 3-legged dog walks into an old west saloon, slides up to the bar and announce 'I'm looking for the man who shot my paw.'",
    "Did you hear about the buddhist who went to the dentist, and refused to take novocain?\nHe wanted to transcend dental medication.",
    "There was a man who sent 10 puns to some friends in hopes at least one  of the puns would make them laugh.\nUnfortunately no pun in ten did!!!",
    "What do you get when you cross a murderer and frosted flakes?\nA cereal killer.",
    "What do you get when you cross a country and an automobile?\nCarnation.",
    "What do you get when you cross a cheetah and a hamburger?\nFast food.",
    "What do you get when you cross finals and a chicken?\nEggs-ams.",
    "What do you get when you cross a rabbit and a lawn sprinkler?\nHare spray.",
    "What do you get when you cross an excited alien and a chicken?\nEggs-cited eggs-traterrestrial",
    "What do you get when you cross an alien and a chicken?\nEggs-traterrestrial.",
    "What do you get when you cross music and an automobile?\nCartune.",
    "I asked my date to meet me at the gym today. She didn't show up.\nThat's when I knew we weren't gonna work out.",
    "Relationships are a lot like algebra. Have you ever looked at your X and wondered Y?",
    "Math Teacher: \"If I have 5 bottles in one hand and 6 in the other hand, what do I have?\nStudent: \"A drinking problem.\"",
    "Before I criticize a man, I like to walk a mile in his shoes.\nThat way, when I do criticize him, I'm a mile away and I have his shoes.",
    "When my boss asked me who is the stupid one, me or him?\nI told him everyone knows he doesn't hire stupid people.","I think my neighbor is stalking me as she's been googling my name on her computer.\nI saw it through my telescope last night.",
    "What does a liar do after he dies? He lies still.",
    "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.","I have a few jokes about unemployed people but it doesn't matter none of them work.",
    "Artificial intelligence is no match for natural stupidity.",
    "The first computer dates back to Adam and Eve.\nIt was an Apple with limited memory, just one byte. And then everything crashed.",
    "\"Doctor, there's a patient on line 1 that says he's invisible.\"\n\"Well, tell him I can't see him right now.\"","I dreamed about drowning in an ocean made out of orange soda last night.\nIt took me a while to figure out it was just a Fanta sea.",
    "Don't spell part backwards. It's a trap.",
    "Going to church doesn't make you a Christian any more than standing in a garage makes you a car.",
    "Just read that 4,153,237 people got married last year, not to cause any trouble but shouldn't that be an even number?",
    "Time waits for no man, time is obviously a woman.",
    "Apparently I snore so loudly that it scares everyone in the car I'm driving.","A recent study has found that women who carry a little extra weight live longer than the men who mention it.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Did Noah include termites on the ark?",
    "How did I escape Iraq? Iran.",
    "What do dentist's call their x-rays?\nTooth pics!","Why should you never trust stairs?\nThey're always up to something lol",
    "When does a joke become a \"Dad\" joke?\nWhen it becomes apparent.",
    "The first rule of Alzheimer's Club is...\nWait, where are we again?",
    "What do you get from a pampered cow?\nSpoiled milk!",
    "Why doesn't Dracula have any friends?\nWell, honestly, he's a real pain in the neck...",
    "A horse walks into a bar.\nThe bartender says, \"Why the long face?\"",
    "What kind of shoes does a spy wear?\nSneakers!",
    "I tried to catch fog yesterday...\nMist.",
    "Someone stole my Microsoft Office, and they're gonna pay...\nYou have my Word.",
    "A sandwich walks into a bar.\nThe bartender says, \"Sorry, we don't serve food here!\"",
    "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
    "I went to buy some camo pants but couldn't find any.",
    "I failed math so many times at school, I can't even count.",
    "I was wondering why the frisbee kept getting bigger and bigger, but then it hit me.",
    "I want to die peacefully in my sleep, like my grandfather... Not screaming and yelling like the passengers in his car.",
    "Don't you hate it when someone answers their own questions? I do.",
    "It takes a lot of balls to golf the way I do.",
    "I know they say that money talks, but all mine says is 'Goodbye.'",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "Most people are shocked when they find out how bad I am as an electrician.",
    "I always take life with a grain of salt. And a slice of lemon. And a shot of tequila.",
    "Just burned 2,000 calories. That's the last time I leave brownies in the oven while I nap.",
    "Build a man a fire and he'll be warm for a day. Set a man on fire and he'll be warm for the rest of his life.",
    "Last night my girlfriend was complaining that I never listen to her… or something like that.",
    "I got a new pair of gloves today, but they're both 'lefts', which on the one hand is great, but on the other, it's just not right.",
    "Despite the high cost of living, it remains popular.",
    "A Mexican magician tells the audience he will disappear on the count of three.\nHe says, 'Uno, dos…' and poof! He disappeared without a tres.",
    "A ghost walked into a bar and ordered a shot of vodka. The bartender said, 'Sorry, we don't serve spirits here.'",
    "I bought the world's worst thesaurus yesterday. Not only is it terrible, it's also terrible.",
    "A blind man walked into a bar... and a table... and a chair...",
    "How do you make holy water? You boil the hell out of it.",
    "The man who created autocorrect has died. Restaurant in peace.",
    "My wife likes it when I blow air on her when she's hot, but honestly... I'm not a fan.",
    "Where there's a will, there's a relative.",
    "If money doesn't grow on trees, how come banks have branches?",
    "What happens to a frog's car when it breaks down? It gets toad away.",
    "A computer once beat me at chess. But it was no match for me at kickboxing.",
    "Give a man a fish and you feed him for a day. But teach a man to fish, and you saved yourself a fish, haven't you?",
    "You don't need a parachute to go skydiving. You need a parachute to go skydiving twice.",
    "Women should not have children after 35. Really, 35 children are enough.",
    "Will glass coffins be a success? Remains to be seen.",
    "I don't like cocaine, I just like the way it smells.",
    "Adam & Eve were the first ones to ignore the Apple terms and conditions.",
    "The rotation of Earth really makes my day... and night."
]

const allowedGibberish = [
    "hmmmm",
    "omg",
    "jk",
    "ok",
    "okay",
    "lmao",
    "lol",
    "stfu",
    "wdym",
    "tbh",
    "aiit",
    "hahaha",
    "huh",
    "wtf",
    "yeah",
    "nah",
    "yep",
    "nope",
    "wbu",
    "smh",
    "bruh",
    "bruv",
    "hbd",
    "gtg",
    "g2g",
    "idc",
    "ikr",
    "ily",
    "nvm",
    "tgif",
    "hiya",
    "hi",
    "hey",
    "sup",
    "wassup",
    "oi",
    "heyo",
    "xup",
    "howdy",
    "oh",
    "lwkm",
    "yh",
    "yup",
    "ohk",
    "owkay",
    "okie"
]

const pictureRequest = [
    "Send me your picture.",
    "Post a picture.",
    "Post a selfie.",
    "What do you look like?",
    "Send pics.",
    "Send your selfie.",
    "Are you cute?"
]

module.exports = {
    gibberish,
    convoTrigger,
    convoStarter,
    jokeTrigger,
    jokes,
    allowedGibberish,
    pictureRequest
}